### ISSUE TITLE
Sus

### ISSUE THREAD

**Issue by NoobToolzz** [Chainski/CHINO-PROXY-SCRAPER#3]
This tool looks very similar to mine..
Check mine [here](https://github.com/NoobToolzz/Bloody-Proxy-Scraper)
My old GitHub (BloodyToolzz) got termed so this my new account

**Comment by Chainski** [comment]
Maybe yours was malicious,  afaik this repo is clean kindly check the codebase.

**Comment by NoobToolzz** [comment]
Nah it was because of smth else, you can check my code too, I've updated it over the past few days

**Comment by NoobToolzz** [comment]
Update: I reworked mine a lot now, same tool but moved stuff around and cleaned code.
